[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/dashboard"
  to = "/#dashboard"
  status = 200
  
[[redirects]]
  from = "/offers"
  to = "/#offers"
  status = 200
  
[[redirects]]
  from = "/partners"
  to = "/#partners"
  status = 200
  
[[redirects]]
  from = "/analytics"
  to = "/#analytics"
  status = 200
  
[[redirects]]
  from = "/postback"
  to = "/#postback"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200