FROM node:20-alpine

WORKDIR /app

# Копируем все файлы
COPY . .

# Устанавливаем ВСЕ зависимости (включая dev)
RUN npm install

# Порт
EXPOSE 5000

# Переменные
ENV NODE_ENV=production
ENV PORT=5000

# Запуск
CMD ["npm", "run", "dev"]