# Koyeb deployment configuration for AdLinkPro
app: adlinkpro
services:
  - name: adlinkpro-backend
    type: web
    git:
      repository: github.com/YOUR_USERNAME/AdLinkPro
      branch: main
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8000"
      - name: DATABASE_URL
        value: "${DATABASE_URL}"
      - name: JWT_SECRET
        value: "${JWT_SECRET}"
      - name: SESSION_SECRET
        value: "${SESSION_SECRET}"
    regions:
      - fra
    instance_type: free
    scale:
      min: 1
      max: 1
    health_check:
      http:
        port: 8000
        path: /health
    build:
      commands:
        - npm install
        - npm run build
    run:
      command: npm start