name: affiliate-marketing-platform
services:
  - name: app
    type: web
    build:
      dockerfile: Dockerfile.koyeb.final
    ports:
      - port: 5000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
      - key: PORT  
        value: "5000"
    health_check:
      http:
        path: /api/health
        port: 5000
    scaling:
      min: 1
      max: 1