name: affiliate-marketing-platform
services:
  - name: app
    type: web
    build:
      dockerfile: Dockerfile.koyeb.simple
    ports:
      - port: 8000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
      - key: PORT  
        value: "8000"
    health_check:
      http:
        path: /api/health
        port: 8000
    scaling:
      min: 1
      max: 1