[build]
  base = ""
  command = "npm ci && npm run build:client"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://central-matelda-pronto12-95b8129d.koyeb.app"
