[build]
command = "npm ci && npm run build:client"
publish = "client/dist"

[[redirects]]
from = "/api/*"
to = "https://central-matelda-pronto12-95b8129d.koyeb.app/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
