[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://central-matelda-pronto12-95b8129d.koyeb.app/api/:splat"
  status = 200
  force = true
