[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "https://central-matelda-pronto12-95b8129d.koyeb.app/:splat"
  status = 200
  force = true
