[build]
# Стартовать сборку из папки client
base = "client"
# Папка, которую надо публиковать (относительно base)
publish = "dist"
# Команда сборки (выполнится внутри client/)
command = "npm ci && npm run build"
