[build]
  base = ""
  command = "npm ci && npm run build:client"
  publish = "client/dist"

# Проксируем все /api/* на Koyeb
[[redirects]]
  from = "/api/*"
  to = "https://central-matelda-pronto12-95b8129d.koyeb.app/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
