[build]
  base = "client"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://central-matelda-pronto12-95b8129d.koyeb.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
