[build]
  base = ""
  command = "npm ci && npm run build:client"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"

# Прокси API на Koyeb
[[redirects]]
  from = "/api/*"
  to = "https://central-matelda-pronto12-95b8129d.koyeb.app/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (на будущее) прокси WS, когда включим сокеты на бэке
[[redirects]]
  from = "/ws"
  to = "wss://central-matelda-pronto12-95b8129d.koyeb.app/ws"
  status = 200
  force = true
