[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  JWT_SECRET = "production-jwt-secret-change-in-production"
  SESSION_SECRET = "production-session-secret"
  SENDGRID_API_KEY = ""
  VOLUUM_TOKEN = ""
  KEITARO_TOKEN = ""
  BINOM_TOKEN = ""
  REDTRACK_TOKEN = ""
  GOOGLE_CLOUD_PROJECT_ID = ""
  GOOGLE_CLOUD_STORAGE_BUCKET = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "dist/"
  node_bundler = "esbuild"