[build]
  command = "npm ci && npm run build:client && cp dist/index.html dist/200.html"
  publish = "dist"

[[redirects]]
from = "/api/*"
to = "https://central-matelda-pronto12-95b8129d.koyeb.app/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
