[build]
  command = "npm ci && npm run build:client"
  publish = "client/dist"

[[redirects]]
  from = "/api/menu/data"
  to = "/menu-default.json"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://central-matelda-pronto12-95b8129d.koyeb.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
