#!/bin/bash

# Test script to validate auto-fix workflow files
# This script simulates what the GitHub Actions workflow will create

echo "🧪 Testing auto-fix workflow file generation..."

KOYEB_URL="https://central-matelda-pronto12-95b8129d.koyeb.app"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="auto-fix/netlify-koyeb-${TIMESTAMP}"

echo "📁 Creating test files with Koyeb URL: ${KOYEB_URL}"

# Create test netlify.toml
cat > test-netlify.toml << EOF
[build]
  command = "npm run build:client"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "${KOYEB_URL}/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Health check proxy
[[redirects]]
  from = "/api/health"
  to   = "${KOYEB_URL}/health"
  status = 200
  force  = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https: wss:; object-src 'none'; base-uri 'self'"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
EOF

# Create test .env.production
cat > test-.env.production << EOF
# === PRODUCTION ENVIRONMENT CONFIGURATION ===
# Auto-generated by GitHub Actions - DO NOT EDIT MANUALLY

# React App Configuration
REACT_APP_API_URL=${KOYEB_URL}/api

# Environment
NODE_ENV=production

# === DEPLOYMENT INFO ===
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Koyeb URL: ${KOYEB_URL}
# Branch: ${BRANCH_NAME}
# Commit: test-commit-sha
EOF

echo "✅ Test files created:"
echo "  - test-netlify.toml"
echo "  - test-.env.production"

echo ""
echo "📋 netlify.toml content:"
echo "----------------------------------------"
head -20 test-netlify.toml

echo ""
echo "📋 .env.production content:"
echo "----------------------------------------"
cat test-.env.production

echo ""
echo "🧪 Validation:"

# Check if netlify.toml contains the right proxy
if grep -q "${KOYEB_URL}/api/:splat" test-netlify.toml; then
    echo "✅ netlify.toml: API proxy configured correctly"
else
    echo "❌ netlify.toml: API proxy missing or incorrect"
fi

# Check if .env.production contains the right API URL  
if grep -q "REACT_APP_API_URL=${KOYEB_URL}/api" test-.env.production; then
    echo "✅ .env.production: API URL configured correctly"
else
    echo "❌ .env.production: API URL missing or incorrect"
fi

# Cleanup
rm -f test-netlify.toml test-.env.production

echo ""
echo "🎉 Auto-fix workflow test completed!"
echo ""
echo "🚀 To run the real workflow:"
echo "  1. Go to GitHub Actions"
echo "  2. Select 'Auto-fix Netlify + Koyeb Configuration'"
echo "  3. Click 'Run workflow'"
echo "  4. Optionally specify custom Koyeb URL"
echo "  5. Click 'Run workflow' button"