// Маппинг стран на ISO коды и флаги
export const COUNTRY_MAPPING: Record<string, { code: string; flag: string; name: string }> = {
  // Русские названия
  'россия': { code: 'RU', flag: '🇷🇺', name: 'Россия' },
  'украина': { code: 'UA', flag: '🇺🇦', name: 'Украина' },
  'беларусь': { code: 'BY', flag: '🇧🇾', name: 'Беларусь' },
  'казахстан': { code: 'KZ', flag: '🇰🇿', name: 'Казахстан' },
  'турция': { code: 'TR', flag: '🇹🇷', name: 'Турция' },
  'германия': { code: 'DE', flag: '🇩🇪', name: 'Германия' },
  'франция': { code: 'FR', flag: '🇫🇷', name: 'Франция' },
  'италия': { code: 'IT', flag: '🇮🇹', name: 'Италия' },
  'испания': { code: 'ES', flag: '🇪🇸', name: 'Испания' },
  'польша': { code: 'PL', flag: '🇵🇱', name: 'Польша' },
  'чехия': { code: 'CZ', flag: '🇨🇿', name: 'Чехия' },
  'венгрия': { code: 'HU', flag: '🇭🇺', name: 'Венгрия' },
  'румыния': { code: 'RO', flag: '🇷🇴', name: 'Румыния' },
  'болгария': { code: 'BG', flag: '🇧🇬', name: 'Болгария' },
  'греция': { code: 'GR', flag: '🇬🇷', name: 'Греция' },
  'сербия': { code: 'RS', flag: '🇷🇸', name: 'Сербия' },
  'хорватия': { code: 'HR', flag: '🇭🇷', name: 'Хорватия' },
  'словения': { code: 'SI', flag: '🇸🇮', name: 'Словения' },
  'словакия': { code: 'SK', flag: '🇸🇰', name: 'Словакия' },
  'литва': { code: 'LT', flag: '🇱🇹', name: 'Литва' },
  'латвия': { code: 'LV', flag: '🇱🇻', name: 'Латвия' },
  'эстония': { code: 'EE', flag: '🇪🇪', name: 'Эстония' },
  'финляндия': { code: 'FI', flag: '🇫🇮', name: 'Финляндия' },
  'швеция': { code: 'SE', flag: '🇸🇪', name: 'Швеция' },
  'норвегия': { code: 'NO', flag: '🇳🇴', name: 'Норвегия' },
  'дания': { code: 'DK', flag: '🇩🇰', name: 'Дания' },
  'нидерланды': { code: 'NL', flag: '🇳🇱', name: 'Нидерланды' },
  'бельгия': { code: 'BE', flag: '🇧🇪', name: 'Бельгия' },
  'австрия': { code: 'AT', flag: '🇦🇹', name: 'Австрия' },
  'швейцария': { code: 'CH', flag: '🇨🇭', name: 'Швейцария' },
  'португалия': { code: 'PT', flag: '🇵🇹', name: 'Португалия' },
  'ирландия': { code: 'IE', flag: '🇮🇪', name: 'Ирландия' },
  'великобритания': { code: 'GB', flag: '🇬🇧', name: 'Великобритания' },
  'канада': { code: 'CA', flag: '🇨🇦', name: 'Канада' },
  'сша': { code: 'US', flag: '🇺🇸', name: 'США' },
  'мексика': { code: 'MX', flag: '🇲🇽', name: 'Мексика' },
  'бразилия': { code: 'BR', flag: '🇧🇷', name: 'Бразилия' },
  'аргентина': { code: 'AR', flag: '🇦🇷', name: 'Аргентина' },
  'чили': { code: 'CL', flag: '🇨🇱', name: 'Чили' },
  'колумбия': { code: 'CO', flag: '🇨🇴', name: 'Колумбия' },
  'перу': { code: 'PE', flag: '🇵🇪', name: 'Перу' },
  'венесуэла': { code: 'VE', flag: '🇻🇪', name: 'Венесуэла' },
  'китай': { code: 'CN', flag: '🇨🇳', name: 'Китай' },
  'япония': { code: 'JP', flag: '🇯🇵', name: 'Япония' },
  'южная корея': { code: 'KR', flag: '🇰🇷', name: 'Южная Корея' },
  'индия': { code: 'IN', flag: '🇮🇳', name: 'Индия' },
  'таиланд': { code: 'TH', flag: '🇹🇭', name: 'Таиланд' },
  'вьетнам': { code: 'VN', flag: '🇻🇳', name: 'Вьетнам' },
  'индонезия': { code: 'ID', flag: '🇮🇩', name: 'Индонезия' },
  'малайзия': { code: 'MY', flag: '🇲🇾', name: 'Малайзия' },
  'сингапур': { code: 'SG', flag: '🇸🇬', name: 'Сингапур' },
  'филиппины': { code: 'PH', flag: '🇵🇭', name: 'Филиппины' },
  'австралия': { code: 'AU', flag: '🇦🇺', name: 'Австралия' },
  'новая зеландия': { code: 'NZ', flag: '🇳🇿', name: 'Новая Зеландия' },
  'израиль': { code: 'IL', flag: '🇮🇱', name: 'Израиль' },
  'саудовская аравия': { code: 'SA', flag: '🇸🇦', name: 'Саудовская Аравия' },
  'оаэ': { code: 'AE', flag: '🇦🇪', name: 'ОАЭ' },
  'египет': { code: 'EG', flag: '🇪🇬', name: 'Египет' },
  'марокко': { code: 'MA', flag: '🇲🇦', name: 'Марокко' },
  'южная африка': { code: 'ZA', flag: '🇿🇦', name: 'Южная Африка' },
  'нигерия': { code: 'NG', flag: '🇳🇬', name: 'Нигерия' },
  'кения': { code: 'KE', flag: '🇰🇪', name: 'Кения' },
  'армения': { code: 'AM', flag: '🇦🇲', name: 'Армения' },
  'грузия': { code: 'GE', flag: '🇬🇪', name: 'Грузия' },
  'азербайджан': { code: 'AZ', flag: '🇦🇿', name: 'Азербайджан' },
  'узбекистан': { code: 'UZ', flag: '🇺🇿', name: 'Узбекистан' },
  'киргизия': { code: 'KG', flag: '🇰🇬', name: 'Киргизия' },
  'таджикистан': { code: 'TJ', flag: '🇹🇯', name: 'Таджикистан' },
  'туркменистан': { code: 'TM', flag: '🇹🇲', name: 'Туркменистан' },
  'молдова': { code: 'MD', flag: '🇲🇩', name: 'Молдова' },

  // Английские названия
  'russia': { code: 'RU', flag: '🇷🇺', name: 'Russia' },
  'ukraine': { code: 'UA', flag: '🇺🇦', name: 'Ukraine' },
  'belarus': { code: 'BY', flag: '🇧🇾', name: 'Belarus' },
  'kazakhstan': { code: 'KZ', flag: '🇰🇿', name: 'Kazakhstan' },
  'turkey': { code: 'TR', flag: '🇹🇷', name: 'Turkey' },
  'germany': { code: 'DE', flag: '🇩🇪', name: 'Germany' },
  'france': { code: 'FR', flag: '🇫🇷', name: 'France' },
  'italy': { code: 'IT', flag: '🇮🇹', name: 'Italy' },
  'spain': { code: 'ES', flag: '🇪🇸', name: 'Spain' },
  'poland': { code: 'PL', flag: '🇵🇱', name: 'Poland' },
  'czech republic': { code: 'CZ', flag: '🇨🇿', name: 'Czech Republic' },
  'czechia': { code: 'CZ', flag: '🇨🇿', name: 'Czechia' },
  'hungary': { code: 'HU', flag: '🇭🇺', name: 'Hungary' },
  'romania': { code: 'RO', flag: '🇷🇴', name: 'Romania' },
  'bulgaria': { code: 'BG', flag: '🇧🇬', name: 'Bulgaria' },
  'greece': { code: 'GR', flag: '🇬🇷', name: 'Greece' },
  'serbia': { code: 'RS', flag: '🇷🇸', name: 'Serbia' },
  'croatia': { code: 'HR', flag: '🇭🇷', name: 'Croatia' },
  'slovenia': { code: 'SI', flag: '🇸🇮', name: 'Slovenia' },
  'slovakia': { code: 'SK', flag: '🇸🇰', name: 'Slovakia' },
  'lithuania': { code: 'LT', flag: '🇱🇹', name: 'Lithuania' },
  'latvia': { code: 'LV', flag: '🇱🇻', name: 'Latvia' },
  'estonia': { code: 'EE', flag: '🇪🇪', name: 'Estonia' },
  'finland': { code: 'FI', flag: '🇫🇮', name: 'Finland' },
  'sweden': { code: 'SE', flag: '🇸🇪', name: 'Sweden' },
  'norway': { code: 'NO', flag: '🇳🇴', name: 'Norway' },
  'denmark': { code: 'DK', flag: '🇩🇰', name: 'Denmark' },
  'netherlands': { code: 'NL', flag: '🇳🇱', name: 'Netherlands' },
  'belgium': { code: 'BE', flag: '🇧🇪', name: 'Belgium' },
  'austria': { code: 'AT', flag: '🇦🇹', name: 'Austria' },
  'switzerland': { code: 'CH', flag: '🇨🇭', name: 'Switzerland' },
  'portugal': { code: 'PT', flag: '🇵🇹', name: 'Portugal' },
  'ireland': { code: 'IE', flag: '🇮🇪', name: 'Ireland' },
  'united kingdom': { code: 'GB', flag: '🇬🇧', name: 'United Kingdom' },
  'uk': { code: 'GB', flag: '🇬🇧', name: 'UK' },
  'canada': { code: 'CA', flag: '🇨🇦', name: 'Canada' },
  'usa': { code: 'US', flag: '🇺🇸', name: 'USA' },
  'united states': { code: 'US', flag: '🇺🇸', name: 'United States' },
  'mexico': { code: 'MX', flag: '🇲🇽', name: 'Mexico' },
  'brazil': { code: 'BR', flag: '🇧🇷', name: 'Brazil' },
  'argentina': { code: 'AR', flag: '🇦🇷', name: 'Argentina' },
  'chile': { code: 'CL', flag: '🇨🇱', name: 'Chile' },
  'colombia': { code: 'CO', flag: '🇨🇴', name: 'Colombia' },
  'peru': { code: 'PE', flag: '🇵🇪', name: 'Peru' },
  'venezuela': { code: 'VE', flag: '🇻🇪', name: 'Venezuela' },
  'china': { code: 'CN', flag: '🇨🇳', name: 'China' },
  'japan': { code: 'JP', flag: '🇯🇵', name: 'Japan' },
  'south korea': { code: 'KR', flag: '🇰🇷', name: 'South Korea' },
  'korea': { code: 'KR', flag: '🇰🇷', name: 'Korea' },
  'india': { code: 'IN', flag: '🇮🇳', name: 'India' },
  'thailand': { code: 'TH', flag: '🇹🇭', name: 'Thailand' },
  'vietnam': { code: 'VN', flag: '🇻🇳', name: 'Vietnam' },
  'indonesia': { code: 'ID', flag: '🇮🇩', name: 'Indonesia' },
  'malaysia': { code: 'MY', flag: '🇲🇾', name: 'Malaysia' },
  'singapore': { code: 'SG', flag: '🇸🇬', name: 'Singapore' },
  'philippines': { code: 'PH', flag: '🇵🇭', name: 'Philippines' },
  'australia': { code: 'AU', flag: '🇦🇺', name: 'Australia' },
  'new zealand': { code: 'NZ', flag: '🇳🇿', name: 'New Zealand' },
  'israel': { code: 'IL', flag: '🇮🇱', name: 'Israel' },
  'saudi arabia': { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia' },
  'uae': { code: 'AE', flag: '🇦🇪', name: 'UAE' },
  'united arab emirates': { code: 'AE', flag: '🇦🇪', name: 'United Arab Emirates' },
  'egypt': { code: 'EG', flag: '🇪🇬', name: 'Egypt' },
  'morocco': { code: 'MA', flag: '🇲🇦', name: 'Morocco' },
  'south africa': { code: 'ZA', flag: '🇿🇦', name: 'South Africa' },
  'nigeria': { code: 'NG', flag: '🇳🇬', name: 'Nigeria' },
  'kenya': { code: 'KE', flag: '🇰🇪', name: 'Kenya' },
  'armenia': { code: 'AM', flag: '🇦🇲', name: 'Armenia' },
  'georgia': { code: 'GE', flag: '🇬🇪', name: 'Georgia' },
  'azerbaijan': { code: 'AZ', flag: '🇦🇿', name: 'Azerbaijan' },
  'uzbekistan': { code: 'UZ', flag: '🇺🇿', name: 'Uzbekistan' },
  'kyrgyzstan': { code: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan' },
  'tajikistan': { code: 'TJ', flag: '🇹🇯', name: 'Tajikistan' },
  'turkmenistan': { code: 'TM', flag: '🇹🇲', name: 'Turkmenistan' },
  'moldova': { code: 'MD', flag: '🇲🇩', name: 'Moldova' },

  // Также добавляем прямые ISO коды
  'ru': { code: 'RU', flag: '🇷🇺', name: 'Russia' },
  'ua': { code: 'UA', flag: '🇺🇦', name: 'Ukraine' },
  'by': { code: 'BY', flag: '🇧🇾', name: 'Belarus' },
  'kz': { code: 'KZ', flag: '🇰🇿', name: 'Kazakhstan' },
  'tr': { code: 'TR', flag: '🇹🇷', name: 'Turkey' },
  'de': { code: 'DE', flag: '🇩🇪', name: 'Germany' },
  'fr': { code: 'FR', flag: '🇫🇷', name: 'France' },
  'it': { code: 'IT', flag: '🇮🇹', name: 'Italy' },
  'es': { code: 'ES', flag: '🇪🇸', name: 'Spain' },
  'pl': { code: 'PL', flag: '🇵🇱', name: 'Poland' },
  'cz': { code: 'CZ', flag: '🇨🇿', name: 'Czech Republic' },
  'hu': { code: 'HU', flag: '🇭🇺', name: 'Hungary' },
  'ro': { code: 'RO', flag: '🇷🇴', name: 'Romania' },
  'bg': { code: 'BG', flag: '🇧🇬', name: 'Bulgaria' },
  'gr': { code: 'GR', flag: '🇬🇷', name: 'Greece' },
  'rs': { code: 'RS', flag: '🇷🇸', name: 'Serbia' },
  'hr': { code: 'HR', flag: '🇭🇷', name: 'Croatia' },
  'si': { code: 'SI', flag: '🇸🇮', name: 'Slovenia' },
  'sk': { code: 'SK', flag: '🇸🇰', name: 'Slovakia' },
  'lt': { code: 'LT', flag: '🇱🇹', name: 'Lithuania' },
  'lv': { code: 'LV', flag: '🇱🇻', name: 'Latvia' },
  'ee': { code: 'EE', flag: '🇪🇪', name: 'Estonia' },
  'fi': { code: 'FI', flag: '🇫🇮', name: 'Finland' },
  'se': { code: 'SE', flag: '🇸🇪', name: 'Sweden' },
  'no': { code: 'NO', flag: '🇳🇴', name: 'Norway' },
  'dk': { code: 'DK', flag: '🇩🇰', name: 'Denmark' },
  'nl': { code: 'NL', flag: '🇳🇱', name: 'Netherlands' },
  'be': { code: 'BE', flag: '🇧🇪', name: 'Belgium' },
  'at': { code: 'AT', flag: '🇦🇹', name: 'Austria' },
  'ch': { code: 'CH', flag: '🇨🇭', name: 'Switzerland' },
  'pt': { code: 'PT', flag: '🇵🇹', name: 'Portugal' },
  'ie': { code: 'IE', flag: '🇮🇪', name: 'Ireland' },
  'gb': { code: 'GB', flag: '🇬🇧', name: 'United Kingdom' },
  'ca': { code: 'CA', flag: '🇨🇦', name: 'Canada' },
  'us': { code: 'US', flag: '🇺🇸', name: 'United States' },
  'mx': { code: 'MX', flag: '🇲🇽', name: 'Mexico' },
  'br': { code: 'BR', flag: '🇧🇷', name: 'Brazil' },
  'ar': { code: 'AR', flag: '🇦🇷', name: 'Argentina' },
  'cl': { code: 'CL', flag: '🇨🇱', name: 'Chile' },
  'co': { code: 'CO', flag: '🇨🇴', name: 'Colombia' },
  'pe': { code: 'PE', flag: '🇵🇪', name: 'Peru' },
  've': { code: 'VE', flag: '🇻🇪', name: 'Venezuela' },
  'cn': { code: 'CN', flag: '🇨🇳', name: 'China' },
  'jp': { code: 'JP', flag: '🇯🇵', name: 'Japan' },
  'kr': { code: 'KR', flag: '🇰🇷', name: 'South Korea' },
  'in': { code: 'IN', flag: '🇮🇳', name: 'India' },
  'th': { code: 'TH', flag: '🇹🇭', name: 'Thailand' },
  'vn': { code: 'VN', flag: '🇻🇳', name: 'Vietnam' },
  'id': { code: 'ID', flag: '🇮🇩', name: 'Indonesia' },
  'my': { code: 'MY', flag: '🇲🇾', name: 'Malaysia' },
  'sg': { code: 'SG', flag: '🇸🇬', name: 'Singapore' },
  'ph': { code: 'PH', flag: '🇵🇭', name: 'Philippines' },
  'au': { code: 'AU', flag: '🇦🇺', name: 'Australia' },
  'nz': { code: 'NZ', flag: '🇳🇿', name: 'New Zealand' },
  'il': { code: 'IL', flag: '🇮🇱', name: 'Israel' },
  'sa': { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia' },
  'ae': { code: 'AE', flag: '🇦🇪', name: 'UAE' },
  'eg': { code: 'EG', flag: '🇪🇬', name: 'Egypt' },
  'ma': { code: 'MA', flag: '🇲🇦', name: 'Morocco' },
  'za': { code: 'ZA', flag: '🇿🇦', name: 'South Africa' },
  'ng': { code: 'NG', flag: '🇳🇬', name: 'Nigeria' },
  'ke': { code: 'KE', flag: '🇰🇪', name: 'Kenya' },
  'am': { code: 'AM', flag: '🇦🇲', name: 'Armenia' },
  'ge': { code: 'GE', flag: '🇬🇪', name: 'Georgia' },
  'az': { code: 'AZ', flag: '🇦🇿', name: 'Azerbaijan' },
  'uz': { code: 'UZ', flag: '🇺🇿', name: 'Uzbekistan' },
  'kg': { code: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan' },
  'tj': { code: 'TJ', flag: '🇹🇯', name: 'Tajikistan' },
  'tm': { code: 'TM', flag: '🇹🇲', name: 'Turkmenistan' },
  'md': { code: 'MD', flag: '🇲🇩', name: 'Moldova' }
};

// Функция для получения информации о стране по названию
export function getCountryInfo(countryName: string): { code: string; flag: string; name: string } | null {
  const normalizedName = countryName.toLowerCase().trim();
  return COUNTRY_MAPPING[normalizedName] || null;
}

// Функция для форматирования массива стран для отображения
export function formatCountries(countries: string[] | string | undefined): Array<{ code: string; flag: string; name: string }> {
  if (!countries) return [];
  
  const countryArray = Array.isArray(countries) ? countries : [countries];
  
  return countryArray.map(country => {
    const info = getCountryInfo(country);
    if (info) {
      return info;
    }
    
    // Если страна не найдена в маппинге, возвращаем как есть с заглушкой
    return {
      code: country.toUpperCase().slice(0, 2),
      flag: '🌐',
      name: country
    };
  });
}

// Функция для получения флага по коду страны (для случаев когда уже есть ISO код)
export function getFlagByCode(countryCode: string): string {
  const upperCode = countryCode.toUpperCase();
  const entry = Object.values(COUNTRY_MAPPING).find(country => country.code === upperCode);
  return entry?.flag || '🌐';
}